
name: redline
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.22.1" # Ensure this range is set correctly

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1 # Example version; replace with the latest compatible version
  image_picker: ^1.1.2 # Example version; replace with the latest compatible version
  firebase_core: ^3.6.0 # Update to match the cloud_firestore requirement
  firebase_auth: ^5.3.1 # This version supports null safety
  firebase_storage: ^12.3.3 # Update to the latest version
  firebase_messaging: ^15.1.3 # Update to the latest version
  cloud_firestore: ^5.4.4 # Ensure this version is compatible with firebase_core
  cupertino_icons: ^1.0.6 # This version supports null safety
  flutter_image_slider:
  swipe_cards: ^2.0.0+1
  intl: ^0.19.0

  pub_updater: ^0.5.0
  google_sign_in: ^6.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/image/logo.png
    - lib/image/profileAvatar.png
