List<String> interests = [
  "Football",
  "Basketball",
  "Tennis",
  "Gun",
  "Sex",
  "Tell you later",
  "Investment",

  "Fishing",
  "Movies",
  "Smoke",
  // Add more interests here
];

List<String> lifestyleInterests = [
  "Travel",
  "Health & Wellness",
  "Fashion",
  "Food & Cooking",
  "Fitness & Exercise",
  "Personal Finance",
  "Home Improvement",
  "Gardening",
  "Sustainability",
  "Beauty & Skincare",
  "Photography",
  "Technology & Gadgets",
  "Art & Design",
  "DIY Projects",
  "Parenting & Family",
  "Mindfulness & Meditation",
  "Books & Literature",
  "Pets & Animals",
  "Music & Entertainment",
  "Sports & Outdoor Activities",
  "Volunteering & Community Service",
  "Interior Design",
  "Cooking & Baking",
  "Camping & Hiking",
  "Cultural Exploration",
  "Networking & Career Development",
  "Language Learning",
  "Gaming & Esports",
  "Social Media & Influencing",
  "Travel Photography",
  "Adventure & Extreme Sports",
  "Luxury Lifestyle",
  "Minimalism",
  "Digital Nomad Lifestyle",
  "Vintage & Retro",
  "Collecting (e.g., stamps, coins, antiques)",
  "Crafting & Handmade Goods",
];

List<String> toysInterests = [
  "Action Figures",
  "Model Kits",
  "Card Games",
  "Puzzle Boxes",
  "Gundam",
  "DIY Electronics Kits",
  "Adult Coloring Books",
  "Drones and UAVs",
  "RC Cars and Trucks",
  "High-Quality Jigsaw Puzzles",
  "Sculpting Tools and Clay",
  "3D Printing",
  "Board Game",
  "Art Supplies (Watercolors, Markers, Canvases)",
  "Guitar and Music Gear (Pedals, Accessories)",
  "Fitness Equipment (Kettlebells, Resistance Bands)",
  "Outdoor Survival Kits",
  "Cooking Gadgets (Sous Vide, Specialty Knives)",
  "Puzzle Games (Rubik's Cube, Brain Teasers)",
  "Virtual Reality Headsets",
  "Cardboard Model Kits",
  "Escape Room Board Games",
  "Model Trains and Railroads",
  "Collectible Coins or Stamps",
  "Electronic Learning Toys for Adults (like Raspberry Pi kits)",
  "Fantasy Role-Playing Game Sets (Dungeons & Dragons)",
  "Knitting or Crafting Kits",
  "Hiking and Outdoor Adventure Gear",
  "Luxury Dice Sets for Gaming",
];
List<String> occupations = [
  "軟體工程師",
  "醫生",
  "老師",
  "護士",
  "會計師",
  "平面設計師",
  "警察",
  "消防員",
  "廚師",
  "電工",
  "建築工人",
  "攝影師",
  "飛行員",
  "律師",
  "藝術家",
  "牙醫",
  "建築師",
  "工程師",
  "藥劑師",
  "作家",
  "音樂家",
  "科學家",
  "水管工",
  "機械師",
  "企業家",
  "治療師",
  "獸醫",
  "記者",
  "運動員",
  "圖書管理員",
];

List<String> exercise = [
  "None",
  "Hiking",
  "Workout",
  "Swimming",
  "Running",
  "Cycling",
  "Yoga",
  "Pilates",
  "Weightlifting",
  "Dancing",
  "Kickboxing",
  "Rock Climbing",
  "Rowing",
  "Jump Rope",
  "Tai Chi",
  "Aerobics",
  "CrossFit",
  "Zumba",
  "Martial Arts",
  "Walking",
  "Surfing",
  "Skiing",
  "Snowboarding",
  "Skating",
  "Scuba Diving",
  "Basketball",
  "Soccer",
  "Tennis",
  "Golf",
  "Baseball",
  "Volleyball",
  "Table Tennis",
  "Frisbee",
  "Gymnastics",
  "Parkour",
  "Ballet",
  "Horseback Riding",
  "Inline Skating",
  "Pilates",
  "Stair Climbing",
  "Spinning",
  "Elliptical Training",
  "Work-Out",
  "Calisthenics",
  "Functional Training",
  "Circuit Training",
  "Iron Man",
];
