// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGLkVD-hMAT_jr1xnCVBP9DDUA6oNOe_s',
    appId: '1:493653584594:android:bafb5c86386bd96e8c1b0b',
    messagingSenderId: '493653584594',
    projectId: 'dating-app-18f5d',
    storageBucket: 'dating-app-18f5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChnG-Z-F-8d04wHZoKg1QoBQI1BNz5z7g',
    appId: '1:493653584594:ios:7453e8e30415d8178c1b0b',
    messagingSenderId: '493653584594',
    projectId: 'dating-app-18f5d',
    storageBucket: 'dating-app-18f5d.appspot.com',
    androidClientId: '493653584594-31fakfmbr886r3josfj12sjr68c55khi.apps.googleusercontent.com',
    iosClientId: '493653584594-s63hj7nf2p05lp6c3hdmhpirg55cs7r6.apps.googleusercontent.com',
    iosBundleId: 'com.example.redline',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLrQzFTj6DOZizuv2_rewdpluYdcyQSxU',
    appId: '1:671046859809:web:9801fa41c6b0d800bbf760',
    messagingSenderId: '671046859809',
    projectId: 'datingapp-f1d4d',
    authDomain: 'datingapp-f1d4d.firebaseapp.com',
    storageBucket: 'datingapp-f1d4d.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2XTOrlAuY1DCfwvInMZEA-vWJtu5ebQA',
    appId: '1:671046859809:ios:3fe4d1e5144e4b3cbbf760',
    messagingSenderId: '671046859809',
    projectId: 'datingapp-f1d4d',
    storageBucket: 'datingapp-f1d4d.appspot.com',
    androidClientId: '671046859809-e1vsdhsteck1i2pgb9n52e8t12uhve55.apps.googleusercontent.com',
    iosClientId: '671046859809-bcc2gadaedc2tpbng2k6rj70qav1gcbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLrQzFTj6DOZizuv2_rewdpluYdcyQSxU',
    appId: '1:671046859809:web:9c047116908b3d47bbf760',
    messagingSenderId: '671046859809',
    projectId: 'datingapp-f1d4d',
    authDomain: 'datingapp-f1d4d.firebaseapp.com',
    storageBucket: 'datingapp-f1d4d.appspot.com',
  );

}